#!/bin/bash -e

# Generate a random string from /dev/urandom
# Arguments:
#  - Desired length (optional)
#  - Possible character space (optional)
#  - Patterns to omit (optional)
function random_string {
  local DEFAULT_SPACE="a-zA-Z0-9"
  local DEFAULT_LEN=12

  local len=${1-$DEFAULT_LEN}
  local space=${2-"$DEFAULT_SPACE"}
  local omit=${3-""}

  local rnd=$(head -n 50 /dev/urandom | tr -dc $space | fold -w $len)
  [ -n "${omit}" ] && rnd=$(echo "${rnd}" | grep -v "${omit}")
  echo $(echo "${rnd}" | head -n1)
}

# Generate a password
# Arguments:
#  - Desired length (optional)
#  - Character space (optional)
#  - Ignore pattern (optional)
function generate_password {
  local DEFAULT_LEN=12
  local DEFAULT_CHAR="a-np-zA-NP-Z1-9-_" #Dash, underscore, Alphanumeric except o,O,0
  local DEFAULT_IGNORE="^-"

  echo $(random_string ${1-$DEFAULT_LEN} ${2-$DEFAULT_CHAR} ${3-$DEFAULT_IGNORE})
}

function initialize_mariadb() {
  if [ ! -f /var/lib/mysql/.created ]; then
    function wait_for_mysqld_start {
      for i in {1..30}; do
        if echo 'select 1' | mysql -u root > /dev/null 2>&1; then
          return 0
        fi
        sleep 1
      done

      echo "MariaDB did not start in time"
      exit 1
    }

    password=$(generate_password)
    dbname=${APP_NAME:-master}

    /usr/bin/mysql_install_db -u root

    /usr/libexec/mysqld &
    pid=$!

    wait_for_mysqld_start

    echo "Creating database $dbname ..."
    echo "Mysql password will be $password"
    echo "$password" > /var/lib/mysql/.password

    sql=$(cat <<SQL
  drop database if exists test;
  create database \`$dbname\`
     DEFAULT CHARACTER SET utf8 DEFAULT
     COLLATE utf8_general_ci;
SQL
)
    echo $sql | mysql -u root

    #delete from user;

    sql=$(cat <<SQL
    delete from user where user='';
    grant all on *.* to 'mysql'@'localhost' identified by '$password' with grant option;
    grant all on *.* to 'mysql'@'%' identified by '$password' with grant option;
    flush privileges;
SQL
)
    echo $sql | mysql -u root mysql

    touch /var/lib/mysql/.created
    kill -TERM $pid

    echo "Starting mysqld ..."
  fi
}

initialize_mariadb

exec /usr/libexec/mysqld
